#!/usr/bin/env bash
# performance-smoke.sh — STUB. A basic latency smoke test against a perf target.
#
# ============================================================================
# TODO: customize for this project's stack.
# ----------------------------------------------------------------------------
# This stub measures request latency against a single HTTP endpoint with curl
# timing and compares p95 against an SLA. Replace / extend for your project:
#   1. {{PERF_TARGET}} — the URL to probe (e.g. http://127.0.0.1:8080/health).
#      Set via env PERF_TARGET, or hard-code where marked. May also encode the
#      signal that matters (e.g. "/health p95 < 200ms") — translate that into
#      PERF_TARGET (the URL) and PERF_P95_SLA_MS (the threshold) below.
#   2. SERVER STARTUP — if you need to boot the app first, add it (this stub
#      assumes the target is already running and degrades gracefully if not).
# ============================================================================
#
# Usage: ai/scripts/performance-smoke.sh <id> <slug>
# Writes a report under testing-reports/. Exits 0 PASS, 1 FAIL/BLOCKED.

set -u

if [ "$#" -lt 2 ]; then
  echo "Usage: $0 <id> <slug>" >&2
  exit 1
fi

ID="$1"
SLUG="$2"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
DATE_STR="$(date +%F)"
STAMP="$(date +%Y%m%d_%H%M%S)"
SAFE_ID="$(echo "$ID" | tr '[:upper:]' '[:lower:]')"
ARTIFACT_DIR="$ROOT_DIR/testing-reports/artifacts/${DATE_STR}_${SAFE_ID}_${SLUG}_${STAMP}"
LATENCY_LOG="$ARTIFACT_DIR/latency-ms.log"
SUMMARY_FILE="$ARTIFACT_DIR/summary.md"

# shellcheck source=ai/scripts/lib/redact.sh
source "$SCRIPT_DIR/lib/redact.sh"

# TODO: set PERF_TARGET in the environment, or replace this placeholder default.
PERF_TARGET_DEFAULT="{{PERF_TARGET}}"
PERF_TARGET="${PERF_TARGET:-$PERF_TARGET_DEFAULT}"
PERF_REQUEST_COUNT="${PERF_REQUEST_COUNT:-40}"
PERF_P95_SLA_MS="${PERF_P95_SLA_MS:-400}"

mkdir -p "$ARTIFACT_DIR"

write_blocked() {
  {
    echo "# PERFORMANCE SMOKE Summary"
    echo
    echo "- Outcome: BLOCKED"
    echo "- Reason: $1"
    echo "- ID: $ID / Feature: $SLUG"
  } > "$SUMMARY_FILE"
  echo "Summary: $SUMMARY_FILE"
}

if ! command -v curl >/dev/null 2>&1; then
  write_blocked "curl is not installed."
  exit 1
fi

if [ "$PERF_TARGET" = "{{PERF_TARGET}}" ] || [ -z "$PERF_TARGET" ] || [ "$PERF_TARGET" = "N/A" ]; then
  write_blocked "PERF_TARGET not configured (placeholder still present). Set PERF_TARGET to the URL to probe."
  exit 1
fi

# Reachability probe.
if ! curl -fsS --connect-timeout 10 --max-time 30 "$PERF_TARGET" >/dev/null 2>&1; then
  write_blocked "Target not reachable: $PERF_TARGET"
  exit 1
fi

# Collect latency samples (ms).
: > "$LATENCY_LOG"
for _ in $(seq 1 "$PERF_REQUEST_COUNT"); do
  TIME_TOTAL="$(curl -s --connect-timeout 10 --max-time 30 -o /dev/null -w '%{time_total}' "$PERF_TARGET" 2>/dev/null || echo 0)"
  TIME_MS="$(awk -v s="$TIME_TOTAL" 'BEGIN { printf "%.0f", s * 1000 }')"
  echo "$TIME_MS" >> "$LATENCY_LOG"
done
redact_file "$LATENCY_LOG"

COUNT="$(wc -l < "$LATENCY_LOG" | tr -d ' ')"
SORTED_LATENCY="$ARTIFACT_DIR/latency-sorted-ms.log"
sort -n "$LATENCY_LOG" > "$SORTED_LATENCY"
P95_INDEX="$(awk -v n="$COUNT" 'BEGIN { idx = int(n * 95 / 100); if (idx < 1) idx = 1; if (idx > n) idx = n; printf "%d", idx }')"
P95_MS="$(sed -n "${P95_INDEX}p" "$SORTED_LATENCY")"
AVG_MS="$(awk '{sum+=$1} END { if (NR>0) printf "%.0f", sum/NR; else print 0 }' "$LATENCY_LOG")"

STATUS="PASS"
EXIT_CODE=0
if [ -z "$P95_MS" ] || [ "$P95_MS" -gt "$PERF_P95_SLA_MS" ]; then
  STATUS="FAIL"
  EXIT_CODE=1
fi

{
  echo "# PERFORMANCE SMOKE Summary"
  echo
  echo "> NOTE: generated by the stub performance-smoke.sh — customize for this stack."
  echo
  echo "- Outcome: $STATUS"
  echo "- Target: $PERF_TARGET"
  echo "- p95 latency ms: $P95_MS"
  echo "- average latency ms: $AVG_MS"
  echo "- Request samples: $COUNT"
  echo "- p95 SLA ms: $PERF_P95_SLA_MS"
  echo "- Latency samples: \`$LATENCY_LOG\`"
} > "$SUMMARY_FILE"

echo "Artifacts written to: $ARTIFACT_DIR"
echo "Summary: $SUMMARY_FILE"
exit "$EXIT_CODE"
