#!/usr/bin/env bash
# security-review.sh — STUB. A starting point for a per-project security regression pack.
#
# ============================================================================
# TODO: customize for this project's stack.
# ----------------------------------------------------------------------------
# This stub is intentionally generic and degrades gracefully when tools are
# missing. Replace / extend the marked sections for your project:
#   1. {{SECURITY_SCAN_COMMAND}} — your dependency / SAST scan (e.g. `npm audit`,
#      `pip-audit`, `cargo audit`, `gosec ./...`). Set it via the env var
#      SECURITY_SCAN_COMMAND, or hard-code it where marked below.
#   2. CHANGED-FILE GREPS — add patterns that matter for your domain
#      (hardcoded secrets, disabled auth, raw SQL, etc.).
#   3. TARGETED TESTS — invoke the security-relevant slice of your test suite.
# ============================================================================
#
# Usage: ai/scripts/security-review.sh <id> <slug>
# Writes an artifact directory + summary under testing-reports/. Returns nonzero
# only when a real scan failure / finding is detected (never just "tool absent").

set -u

if [ "$#" -lt 2 ]; then
  echo "Usage: $0 <id> <slug>" >&2
  exit 1
fi

ID="$1"
SLUG="$2"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
DATE_STR="$(date +%F)"
STAMP="$(date +%Y%m%d_%H%M%S)"
SAFE_ID="$(echo "$ID" | tr '[:upper:]' '[:lower:]')"
ARTIFACT_DIR="$ROOT_DIR/testing-reports/artifacts/${DATE_STR}_${SAFE_ID}_${SLUG}_${STAMP}"
SUMMARY_FILE="$ARTIFACT_DIR/summary.md"
OVERALL_EXIT=0

# shellcheck source=ai/scripts/lib/redact.sh
source "$SCRIPT_DIR/lib/redact.sh"

mkdir -p "$ARTIFACT_DIR"
{
  echo "# SECURITY REVIEW Evidence Summary"
  echo
  echo "- ID: $ID"
  echo "- Feature: $SLUG"
  echo "- Date: $DATE_STR"
  echo "- Artifact Dir: \`$ARTIFACT_DIR\`"
  echo
  echo "> NOTE: generated by the stub security-review.sh — customize for this stack."
  echo
} > "$SUMMARY_FILE"

# Run a command, capture+redact its log, record it. Never aborts the script.
run_step() {
  local name="$1" cmd="$2"
  local log_file="$ARTIFACT_DIR/${name}.log"
  local exit_code
  {
    printf '$ %s\n\n' "$cmd"
    bash -lc "$cmd"
  } > "$log_file" 2>&1
  exit_code=$?
  redact_file "$log_file"
  [ "$exit_code" -ne 0 ] && OVERALL_EXIT=1
  {
    echo "## $name"
    echo "- Command: \`$cmd\`"
    echo "- Exit code: $exit_code"
    echo "- Log: \`$log_file\`"
    echo
  } >> "$SUMMARY_FILE"
  return 0
}

# --- Repo context (always safe) -------------------------------------------------------
if command -v git >/dev/null 2>&1 && git -C "$ROOT_DIR" rev-parse >/dev/null 2>&1; then
  run_step "git_sha" "cd '$ROOT_DIR' && git rev-parse HEAD"
  run_step "git_status" "cd '$ROOT_DIR' && git status --short"
fi

# --- 1. Dependency / SAST scan --------------------------------------------------------
# TODO: set SECURITY_SCAN_COMMAND in the environment, or replace this default below.
SECURITY_SCAN_COMMAND_DEFAULT="{{SECURITY_SCAN_COMMAND}}"
SECURITY_SCAN_COMMAND="${SECURITY_SCAN_COMMAND:-$SECURITY_SCAN_COMMAND_DEFAULT}"
if [ "$SECURITY_SCAN_COMMAND" = "{{SECURITY_SCAN_COMMAND}}" ] || [ -z "$SECURITY_SCAN_COMMAND" ] || [ "$SECURITY_SCAN_COMMAND" = "N/A" ]; then
  {
    echo "## dependency_scan"
    echo "- SKIPPED: SECURITY_SCAN_COMMAND not configured (placeholder still present)."
    echo
  } >> "$SUMMARY_FILE"
else
  run_step "dependency_scan" "cd '$ROOT_DIR' && $SECURITY_SCAN_COMMAND"
fi

# --- 2. Grep changed files for common issues ------------------------------------------
# Determine the changed file set (best effort).
CHANGED_FILES=""
if command -v git >/dev/null 2>&1 && git -C "$ROOT_DIR" rev-parse >/dev/null 2>&1; then
  CHANGED_FILES="$(git -C "$ROOT_DIR" diff --name-only HEAD 2>/dev/null; git -C "$ROOT_DIR" diff --name-only --cached 2>/dev/null)"
  CHANGED_FILES="$(echo "$CHANGED_FILES" | sort -u | sed '/^$/d')"
fi

GREP_LOG="$ARTIFACT_DIR/changed_file_grep.log"
: > "$GREP_LOG"
if [ -z "$CHANGED_FILES" ]; then
  echo "No changed files detected (or not a git repo) — skipping changed-file grep." >> "$GREP_LOG"
else
  GREP_BIN="grep -nE"
  command -v rg >/dev/null 2>&1 && GREP_BIN="rg -n"
  # TODO: extend these patterns for your domain.
  PATTERNS='(api[_-]?key|secret|password|token)\s*[:=]\s*["'\''][^"'\'']+|BEGIN (RSA|EC|OPENSSH|PRIVATE) KEY|eval\(|child_process|TODO[ :]?SECURITY'
  while IFS= read -r f; do
    [ -f "$ROOT_DIR/$f" ] || continue
    echo "### $f" >> "$GREP_LOG"
    $GREP_BIN "$PATTERNS" "$ROOT_DIR/$f" >> "$GREP_LOG" 2>/dev/null || echo "  (no matches)" >> "$GREP_LOG"
  done <<< "$CHANGED_FILES"
fi
redact_file "$GREP_LOG"
{
  echo "## changed_file_grep"
  echo "- Heuristic scan of changed files for hardcoded secrets / risky calls."
  echo "- Log: \`$GREP_LOG\` — review manually; matches are signals, not verdicts."
  echo
} >> "$SUMMARY_FILE"

# --- 3. Targeted security tests -------------------------------------------------------
# TODO: replace with the security-relevant slice of your test suite, e.g.
#   run_step "security_tests" "cd '$ROOT_DIR' && {{TEST_COMMAND}} -- <auth/rbac test paths>"
{
  echo "## targeted_tests"
  echo "- TODO: wire up the security-relevant slice of this project's test suite."
  echo
} >> "$SUMMARY_FILE"

{
  echo "## overall_status"
  echo "- Exit code: $OVERALL_EXIT"
  echo
} >> "$SUMMARY_FILE"

echo "Artifacts written to: $ARTIFACT_DIR"
echo "Summary: $SUMMARY_FILE"
exit "$OVERALL_EXIT"
